-- TYPE : Oracle_11
-- NAME : New Oracle
-- DATABASE : xe

CREATE TABLE SIGHTS (
	TITLE VARCHAR2(400) NOT NULL PRIMARY KEY,
	SEQ NUMBER NOT NULL ,
	CATEGORY NUMBER(10) NOT NULL,
	THEME VARCHAR2(400) NOT NULL,
	FILENAME VARCHAR2(400),
	ADDRESS VARCHAR2(400) ,
	PHONE VARCHAR2(400) ,
	HOMEPAGE VARCHAR2(400) ,
	CONTENT VARCHAR2(4000) ,
	ADDSCHEDULE NUMBER(20),
	DEL NUMBER(20),
	READCOUNT NUMBER(20)
);
--DROP TABLE SIGHTS CASCADE CONSTRAINTS;
--관광지이름, 관광지고유번호, 관광지종류, 관광지테마, 사진파일경로, 관광지주소, 관광지전화, 관광지홈페이지, 관광지설명, 일정추가횟수, 삭제여부, 조회수

CREATE SEQUENCE SEQ_SIGHTS

SELECT * FROM SIGHTS;
SELECT * FROM SIGHTS WHERE THEME='cafe';

SELECT RNUM, TITLE, SEQ, CATEGORY, THEME, FILENAME, ADDRESS, PHONE, HOMEPAGE, CONTENT, ADDSCHEDULE, DEL, READCOUNT 
FROM ( 
	SELECT ROWNUM AS RNUM, TITLE, SEQ, CATEGORY, THEME, FILENAME, ADDRESS, PHONE, HOMEPAGE, CONTENT, ADDSCHEDULE, DEL, READCOUNT 
	FROM ( SELECT * FROM SIGHTS WHERE CATEGORY = 0 AND THEME='nature')
	ORDER BY SEQ DESC 
)
WHERE ( (RNUM >= 1) AND (RNUM <= 7) ) 

SELECT ROWNUM AS RNUM, TITLE, SEQ, CATEGORY, THEME, FILENAME, ADDRESS, PHONE, HOMEPAGE, CONTENT, ADDSCHEDULE, DEL, READCOUNT FROM SIGHTS ORDER BY SEQ DESC;

SELECT COUNT(*)
FROM SIGHTS
WHERE THEME='nature'
AND CATEGORY=0


--SELECT DISTINCT THEME
--FROM SIGHTS
--WHERE CATEGORY=1

--SELECT *
--FROM SIGHTS
--WHERE CATEGORY=1
--AND THEME='cafe'
--ORDER BY READCOUNT DESC




INSERT INTO SIGHTS
VALUES('우도', SEQ_SIGHTS.NEXTVAL, 0, 'nature', 'udo.jpg', 
			'제주특별자치도 제주시 우도면 삼양고수물길 1', '(+82) 064-782-5671', 'hompage', '우도content', 0, 0, 0);

INSERT INTO SIGHTS
VALUES('성산일출봉', SEQ_SIGHTS.NEXTVAL, 0, 'nature', 'sungsan.jpg', 
			'제주특별자치도 서귀포시 성산읍 일출로 284-12', '(+82) 064-783-0959', 'hompage', '성산일출봉content', 0, 0, 0);

INSERT INTO SIGHTS
VALUES('봄날카페', SEQ_SIGHTS.NEXTVAL, 1, 'cafe', 'springday.jpg', 
			'제주특별자치도 제주시 애월읍 애월로1길 25', '(+82) 064-799-4999', 'https://blog.naver.com/jejubomnal', '봄날카페content', 0, 0, 0);
			
INSERT INTO SIGHTS
VALUES('명진전복', SEQ_SIGHTS.NEXTVAL, 1, 'food', 'myengjin.jpg', 
			'제주특별자치도 제주시 구좌읍 해맞이해안로 1282', '(+82) 064-782-9944', '없음', '명진전복content', 0, 0, 0);			

INSERT INTO SIGHTS
VALUES('몽상드애월', SEQ_SIGHTS.NEXTVAL, 1, 'cafe', 'monsangde.jpg', 
			'제주특별자치도 제주시 애월읍 애월북서길 56-1', '(+82) 064-799-8900', '없음', '몽상드애월content', 1, 0, 1);
			
INSERT INTO SIGHTS
VALUES('사려니숲길', SEQ_SIGHTS.NEXTVAL, 0, 'nature', 'saryeni.jpg', 
			'제주특별자치도 제주시 조천읍 교래리 산 137-1', '(+82) 064-900-8800', '없음', '사려니숲길content', 2, 0, 1);

			
			
INSERT INTO SIGHTS
VALUES('카멜리아힐', SEQ_SIGHTS.NEXTVAL, 0, 'nature', 'camelliahil.jpg', 
			'제주 서귀포시 안덕면 병악로 166', '(+82) 064-792-0088', 'https://www.camelliahill.co.kr/', '사려니숲길content', 3, 0, 2);			

			


INSERT INTO SIGHTS
VALUES('관덕정', SEQ_SIGHTS.NEXTVAL, 0, 'tour', 'Gwandeokjeong.jpg', 
			'제주특별자치도 제주시 관덕로 19', '(+82) 064-710-6711', 'http://culture.jejusi.go.kr/', '관덕정content', 4, 0, 3);		
			
INSERT INTO SIGHTS
VALUES('아침미소목장', SEQ_SIGHTS.NEXTVAL, 0, 'leisure', 'morningsmilefarm.jpg', 
			'제주특별자치도 제주시 첨단동길 160-20', '(+82) 064-727-2545', 'https://morningsmile.modoo.at/', '아침미소content', 5, 0, 1);
			
INSERT INTO SIGHTS
VALUES('한라산영실코스', SEQ_SIGHTS.NEXTVAL, 0, 'walk', 'hanlasanyeongsil.jpg', 
			'제주특별자치도 서귀포시 영실로 246', '(+82) 064-747-9950', '없음', '한라산영실코스content', 6, 0, 3);	



INSERT INTO SIGHTS
VALUES('더럭초등학교', SEQ_SIGHTS.NEXTVAL, 0, 'photo', 'hanlasanyeongsil.jpg', 
			'제주특별자치도 제주시 애월읍 하가로 195', '(+82) 064-799-0515', 'http://aewol.jje.es.kr/aewol-e/0801/board/10823', '더럭분교content', 7, 0, 7);				
			
UPDATE SIGHTS
SET FILENAME='deoleogschool.jpg'
WHERE TITLE='더럭초등학교'		


SELECT COUNT(*)  FROM SIGHTS WHERE CATEGORY=0
			
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME) VALUES('테스트타이틀', SEQ_SIGHTS.NEXTVAL, 0, '테스트테마');





---------------------


-- TYPE : Oracle_11
-- NAME : New Oracle
-- DATABASE : xe
SELECT * FROM SIGHTS;
CREATE TABLE SIGHTS (
        TITLE VARCHAR2(400) NOT NULL PRIMARY KEY,
        SEQ NUMBER(10) NOT NULL ,
        CATEGORY NUMBER(10) NOT NULL,
        THEME VARCHAR2(400) NOT NULL,
        FILENAME VARCHAR2(4000),
        ADDRESS VARCHAR2(400) ,
        PHONE VARCHAR2(400) ,
        HOMEPAGE VARCHAR2(400) ,
        CONTENT VARCHAR2(4000) ,
        ADDSCHEDULE NUMBER(20),
        DEL NUMBER(20),
        READCOUNT NUMBER(20),
        LIKECOUNT NUMBER(20)
);
--DROP TABLE SIGHTS CASCADE CONSTRAINTS;
--관광지이름, 관광지고유번호, 관광지종류, 관광지테마, 사진파일경로, 관광지주소, 관광지전화, 관광지홈페이지, 관광지설명, 일정추가횟수, 삭제여부, 조회수
CREATE SEQUENCE SEQ_SIGHTS START WITH 1 MAXVALUE 9999999999 INCREMENT BY 1;

SELECT * FROM SIGHTS WHERE CATEGORY= 2 AND SEQ>=0 AND SEQ<=5 ;

 SELECT TITLE, SEQ, CATEGORY, THEME
 FROM (SELECT ROW_NUMBER()OVER(ORDER BY SEQ ASC) AS RNUM
 ,TITLE, SEQ, CATEGORY, THEME FROM SIGHTS  WHERE CATEGORY= 0 )	
WHERE RNUM >= 10  AND RNUM <= 20  


SELECT SEQ, TITLE, THEME, ADDRESS FROM 
				 (SELECT ROW_NUMBER()OVER(ORDER BY SEQ ASC) AS RNUM ,
				 SEQ, TITLE,  THEME, ADDRESS FROM SIGHTS WHERE CATEGORY= 1)
				 WHERE RNUM >= 1  AND RNUM <= 5 
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME) VALUES('테스트타이틀', SEQ_SIGHTS.NEXTVAL, 0, '테스트테마');
SELECT TITLE,SEQ,ADDSCHEDULE FROM SIGHTS  WHERE ADDSCHEDULE IS NOT NULL ORDER BY ADDSCHEDULE DESC;

--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME, ADDRESS,ADDSCHEDULE) VALUES('노리매공원', SEQ_SIGHTS.NEXTVAL, 0, '테스트테마','제주시 우도면',4);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME, ADDRESS,ADDSCHEDULE) VALUES('새연교', SEQ_SIGHTS.NEXTVAL, 0, '테스트테마','제주시 우도면',8);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME, ADDRESS,ADDSCHEDULE) VALUES('보롬왓', SEQ_SIGHTS.NEXTVAL, 0, '테스트테마','제주시 우도면',10);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME, ADDRESS,ADDSCHEDULE) VALUES('김녕해수욕장', SEQ_SIGHTS.NEXTVAL, 0, '테스트테마','제주시 우도면',0);
--
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME,ADDSCHEDULE) VALUES('노리', SEQ_SIGHTS.NEXTVAL, 0, 'nature',1);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME,ADDSCHEDULE) VALUES('새연교공원', SEQ_SIGHTS.NEXTVAL, 0, 'nature',40);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME,ADDSCHEDULE) VALUES('김녕해수욕', SEQ_SIGHTS.NEXTVAL, 0, 'nature',45);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME,ADDSCHEDULE) VALUES('천지연폭포공원', SEQ_SIGHTS.NEXTVAL, 0, 'nature',42);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME,ADDSCHEDULE) VALUES('폭포공원', SEQ_SIGHTS.NEXTVAL, 0, 'nature',2);
--INSERT INTO SIGHTS (TITLE, SEQ, CATEGORY, THEME,ADDSCHEDULE) VALUES('제주바다', SEQ_SIGHTS.NEXTVAL, 0, 'nature',8);
