-- TYPE : Oracle_11
-- NAME : New Oracle
-- DATABASE : xe

CREATE TABLE MEMBER_JEJU (
	ID VARCHAR2(400) NOT NULL PRIMARY KEY,
	SEQ NUMBER NOT NULL,
	PW VARCHAR2(400) NOT NULL,
	NAME VARCHAR2(400) ,
	EMAIL VARCHAR2(400) ,
	BIRTH VARCHAR2(400) ,
	DEL NUMBER(4),
	ISADMIN NUMBER(4)
);
--DROP TABLE MEMBER_JEJU CASCADE CONSTRAINTS;
--ISADMIN : 관리자인 경우 3, 일반회원은 1
--DEL : 삭제회원은 1, 정상회원은 0

CREATE SEQUENCE SEQ_MEMBER_JEJU START WITH 1 MAXVALUE 9999999999 INCREMENT BY 1;
--DROP SEQUENCE SEQ_MEMBER_JEJU;


SELECT * FROM MEMBER_JEJU;

--INSERT INTO MEMBER_JEJU (ID, SEQ, PW, NAME, EMAIL, BIRTH, DEL, ISADMIN) VALUES(	'admin', SEQ_MEMBER_JEJU.NEXTVAL, 'admin', '관리자', '1@1.1', '1991-02-18', 0, 3);
