-- TYPE : Oracle_11
-- NAME : New Oracle
-- DATABASE : xe

CREATE TABLE SCHEDULES (
	SEQ NUMBER NOT NULL PRIMARY KEY,
	ID VARCHAR2(400) NOT NULL,
	TITLE VARCHAR2(400) NOT NULL,
	SDATE VARCHAR2(400) ,
	EDATE VARCHAR2(400) ,
	TOTALDAYS VARCHAR2(400),
	MEMBER VARCHAR2(400),
	COMPANION VARCHAR2(400),
	SECTION VARCHAR2(400),
	OPEN NUMBER,
	WDATE DATE
);
--DROP TABLE SCHEDULES CASCADE CONSTRAINTS;
--여행일정번호, 작성자, 일정제목, 일정시작일, 일정종료일, 작성일

SELECT * FROM SCHEDULES

CREATE SEQUENCE SEQ_SCHEDULES START WITH 1 MAXVALUE 9999999999 INCREMENT BY 1;
--DROP SEQUENCE SEQ_SCHEDULES

SELECT SEQ, ID, TITLE, SDATE, EDATE, TOTALDAYS, MEMBER, COMPANION, SECTION, OPEN, WDATE 
FROM SCHEDULES WHERE TITLE LIKE '%정현아%'  ORDER BY WDATE  DESC 

--INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );

INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'aaa', '우', '2019-08-06', '2019-08-07', SYSDATE );
INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );
INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );
INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );
INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );
INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );
INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, WDATE) VALUES( SEQ_SCHEDULES.NEXTVAL, 'admin', '테스트일정', '2019-08-06', '2019-08-07', SYSDATE );

DELETE  FROM SCHEDULES WHERE SEQ=1


SELECT * FROM SCHEDULES WHERE SDATE > SYSDATE


 INSERT INTO SCHEDULES (SEQ, ID, TITLE, SDATE, EDATE, TOTALDAYS,
				 MEMBER, COMPANION, SECTION, OPEN, WDATE )
				VALUES( SEQ_SCHEDULES.NEXTVAL, '111', '제주여행' ,'05/09/2019' ,'05/09/2019' ,1, 1,'부모' ,'레저',1 ,SYSDATE)

	SELECT SEQ_SCHEDULES.CURRVAL FROM DUAL;

 UPDATE SCHEDULES SET  ID='1', TITLE='1' ,
 SDATE= '1', EDATE = ?, TOTALDAYS ='1',  MEMBER ='1' , COMPANION= '1', SECTION= '1', OPEN= '1'
	 WHERE SEQ= 2 
	
SELECT SEQ FROM SCHEDULES WHERE ID='hwwk78' AND TITLE='반가웡' AND SDATE='08/13/2019' AND EDATE='08/17/2019'